name: Integration Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update action.yml to build locally
        run: |
          sed -i 's/.*image\:.*/  image\: \"Dockerfile\"/' action.yml
          cat action.yml
      - name: Self test
        id: selftest
        uses: ./
        with:
          include: "test/**"
          find: "https://avatars.githubusercontent.com/u/([0-9]+)\?v=4"
          target: "$1.png"
      - name: Check outputs and modified files
        run: |
          test -f test/1056435.pngc
          test "${{ steps.selftest.outputs.modifiedFiles }}" == "1"
          grep "hello 1056435?.png !" test/hello.txt
